theme: jekyll-theme-midnight
name: Sam Hildebrand's blog
timezone: America/Chicago
baseurl: /the-blog/
permalink: :categories/:year/:month/:day/:title/
google_analytics: UA-166133460-2
layout: default
future: false
