theme: jekyll-theme-midnight
name: Sam Hildebrand's blog
timezone: America/Chicago
permalink: https://sam-hildebrand.github.io/the-blog/:categories/:year/:month/:day/:title:output_ext
google_analytics: UA-166133460-2
